### ISSUE TITLE
release TODO

### ISSUE THREAD

**Issue by hannesm** [mirleft/ocaml-tls#94]
we should pack up a release. things which should be addressed before:
## hardening / crypto
- [ ] verify mitigations for #31 and other security-relevant issues
- [x] seed for rng / reseed constantly (at least in lwt) <- david, seed only: reseed is hard
- [x] [proof](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.21.1971) DH <- david
- [ ] nocrypto cleanups? (maybe replace that sha thingy) <- david, time permitting
- [ ] hook up GCM? <- david, time permitting
## completeness / bugs
- [x] x509 verification time <- david, with a cameo by @dbuenzli 
- [x] x509 verification wildcard hostnames (example: www.opendylan.org:443) <- hannes
- [x] x509 verification of keyusage, depending on key exchange algorithm <- hannes
- [x] x509 woes for connecting to www.apple.com:443
- [x] feedback doesn't like packets which are roughly `> 16368 (2 ^ 14 - 16)` (error in server)
- [x] validation of packets <- hannes
- [x] sending with internal fragmentation <- hannes
- [ ] client authentication? (we can defer that to later)
## usability
- [x] configuration interface to require / not require rekeying (to talk to microsoft.com) <- hannes
- [ ] ocamldoc on signatures
- [ ] configuration option examples: only accept n-bit certificates, no md5 (in X509 / handshake), no RC4, no CBC
- [x] split out state/session creation into `Config`, add validation there <- david
- [x] validation of configuration (RSA key exchange requires RSA certificate and private key with appropriate attributes (usable for encipherment)) <- david
- [x] config: allow specification of a certificate chain which is send over by the server to the client
